### ISSUE TITLE
Missed dot in import?

### ISSUE THREAD

**Issue by denkorzh** [marcotcr/anchor#1]
installed package with pip.
When running 'Anchor on tabular data.ipynb' I get an error

```
----> 1 import anchor_base
      2 import anchor_explanation
      3 import utils
      4 import lime
      5 import lime.lime_tabular

ModuleNotFoundError: No module named 'anchor_base'
```
Possibly you have missed a dot in import statement

**Comment by marcotcr** [comment]
Not only had I missed a dot, I forgot to test this using python3. Should be fixed now, thanks.
