### ISSUE TITLE
Precision & Coverage Issue, Possible effects on anchor?

### ISSUE THREAD

**Issue by GDPlumb** [marcotcr/anchor#10]
I was running playing around with Anchors and was getting really weird coverage and precision values.  Then I saw the TODO (line 301 of anchor_tabular.py) saying that the precision and coverage measures are incorrect.  

Does this mean that the anchors that I computed were also wrong?  Or does the issue only affect those metrics?

Thanks!

**Comment by marcotcr** [comment]
That is a note on the precision and coverage of intermediate anchors, especially for when features are ordinal or numerical. Are you seeing weird coverage / precision values on the final anchors produced?

**Comment by GDPlumb** [comment]
Here it is (should be .py)

[AnchorExperiment.txt](https://github.com/marcotcr/anchor/files/1881411/AnchorExperiment.txt)

**Comment by GDPlumb** [comment]
Is the way I set up the code incorrect?  If not, what would you suggest doing?

Thanks!

**Comment by marcotcr** [comment]
Sorry for the long delay in responding to this. The way you setup the code is not incorrect, there was in fact an error in how I was sampling numerical features that get discretized.
I fixed it and updated the package, would you mind trying again? Please reopen the issue if it is not fixed.

For your example, quartiles are not enough to get decent anchors, so you may want to try to set `discretizer=decile` in the fit function. Even if you don't, you shouldn't see anchors that do not apply to the points they were generated for, and precision / coverage should be right.
