### ISSUE TITLE
issue with the predict function, classifier problem, categorical dataset

### ISSUE THREAD

**Issue by skavula** [marcotcr/anchor#11]
Hi, I found the paper on anchor extremely interesting. The dataset I have only has categorical features with values 0 and 1. I tested it for different models but the code, throws an error in the line, classifier_fn(self.encoder.transform(x)) . As the feature vectors that the dataset has are already discretized, anchor discretizes it further, irrespective of the input throwing an error from the predict function. Could you please help me with the issue. Thanks.

**Comment by marcotcr** [comment]
Sorry for the delay in responding. Are you using the `categorical_features` parameter with all of your features when initializing the explainer?

If so, can you please share your code?

**Comment by skavula** [comment]
No problem. I am using the categorical_features parameter with all the features in the dataset. 
The dataset has categorical features only. These features when fed to the model are discretized by anchor, and this doubles the number of feature vectors (the original 51 feature vectors are converted into 102 feature vectors). 
<img width="653" alt="screen shot 2018-05-01 at 10 27 38 am" src="https://user-images.githubusercontent.com/34525437/39484664-4b85ccfa-4d2b-11e8-92bd-09fbaf24a22e.png">

clf is a one class SVM model. 
exp = explainer.explain_instance(test_data[idx], clf.predict, threshold=0.95)

The error it throws is :
return classifier_fn(self.encoder.transform(x))

ValueError: cannot use sparse input in 'OneClassSVM' trained on dense data


Thank you.

**Comment by marcotcr** [comment]
I guess I responded to this via email and forgot the thread

**Comment by skavula** [comment]
Hi Marco,

I hope you are doing fine. I had replied to you on github, but I did not
receive any response regarding my question. I was hoping if you could help
me with the issue.

Below is the response to the question you had asked me :

I am using the categorical_features parameter with all the features in the
dataset.
The dataset has categorical features only. These features when fed to the
model are discretized by anchor, and this doubles the number of feature
vectors (the original 51 feature vectors are converted into 102 feature
vectors).
[image: screen shot 2018-05-01 at 10 27 38 am]
<https://user-images.githubusercontent.com/34525437/39484664-4b85ccfa-4d2b-11e8-92bd-09fbaf24a22e.png>

clf is a one class SVM model.
exp = explainer.explain_instance(test_data[idx], clf.predict,
threshold=0.95)

The error it throws is :
return classifier_fn(self.encoder.transform(x))

ValueError: cannot use sparse input in 'OneClassSVM' trained on dense data
It would be nice if we could take it from here.

Thank you,
Shaarvani

**Comment by marcotcr** [comment]
how about this, try encapsulating the SVM function:
"""
def predict_fn(data):
  return clf.predict(data.todense())
"""
And use this in explain_instance
