### ISSUE TITLE
Stopping conditions broken

### ISSUE THREAD

**Issue by JonStevensWork** [marcotcr/anchor#15]
When using anchor on my dataset, I have found that it produces an anchor containing conditions in all (73) features. It seems to have identical output to LIME with discretized continuous variables, rather than intelligently choosing a few high coverage, high precision conditions.

You mention in your code that your calculations for precision and coverage are not currently working. So does the stopping condition for the anchor construction algorithm not work, if it uses these? Do you have plans to fix this?

**Comment by marcotcr** [comment]
Hello,
What do you mean by identical output to LIME?
The stopping condition for the anchor construction algorithm should be working, the precision and coverage calculations are not working for intermediate anchors.
I need some more information to understand if this is a bug in here or if the model is really unstable such that there are no high precision conditions (i.e. any feature can be changed enough to change the prediction).

Are you passing in discretized data?
