### ISSUE TITLE
SP-Anchor

### ISSUE THREAD

**Issue by Valenzione** [marcotcr/anchor#18]
Hello Marco,

I find your paper genuinely interesting, it is great progress towards the model-agnostic interpretability.

I wanted to ask you whether this repository is missing the code connected with SP-Anchor?

**Comment by marcotcr** [comment]
Thanks. I guess I didn't include the code in this repository, but it is pretty trivial. Take a look at [this function](https://github.com/marcotcr/anchor-experiments/blob/master/utils.py#L335), although it only works for discretized data (i.e. it will not consider anchors like x > 1, only x == 1), it would need minor modifications for continuous / ordinal features.

**Comment by adityakumar04** [comment]
Hello Marco, 

Could you provide more details on how to use the SP anchor. Also how will the precision and coverage be defined in case of SP -anchor ?
