### ISSUE TITLE
still using LIME?

### ISSUE THREAD

**Issue by amirdaaee** [marcotcr/anchor#19]
Hi Marco,
Although anchor is a great idea and outperforming LIME in experiences, why LIME is still so popular? What are anchor's drawbacks?

**Comment by marcotcr** [comment]
We do have a Limitations section in [the paper](https://homes.cs.washington.edu/~marcotcr/aaai18.pdf). The TL;DR version is that an anchor may be too long and thus useless, while LIME may still give useful insight as to the direction and magnitude of certain features (see Figure 5 for an example).

Also, the code in the LIME repository is much better (my fault, didn't spend much time in this one), and also has been used by way more people (and thus many bugs have been caught and fixed).
