### ISSUE TITLE
Parenthesis on print, anchor_image

### ISSUE THREAD

**Issue by SaraBtt** [marcotcr/anchor#22]
Hi Marco, 
I'm trying to use the anchor_image module on python 3 for my master's thesis.
I have a problem with the "print" command. The parenthesis are missing in all of the print calls.

Which is the package I should install? anchor or anchor_exp? can they be together?

**Comment by marcotcr** [comment]
The version in the repo should work on python3.
You can install it by running
`pip install git+git://github.com/marcotcr/anchor.git`

**Comment by SaraBtt** [comment]
Thanks for the reply, and for the project!:)
