### ISSUE TITLE
Using anchor on pre-processed dataset

### ISSUE THREAD

**Issue by kirilgeorgiev82** [marcotcr/anchor#23]
Hi,

First I want to thank you for the wonderful paper and creating this library in the first place. I would also like to ask a question. 

I want to use anchor on a dataset which is already processed (i.e. everything is binned and properly one-hot encoded so now I have a |'n_cases' x 'm_one-hot-encoded_features'| sparse matrix as (X) and |n_cases x 2| matrix as (y). Unfortunately, there is a lot of 'automated' dataset processing which is done during instatializaton of an anchor_tabular.AnchorTabularExplainer(), which produces various errors when I want to use it on an arbitrary dataset. 

Can you please advise what one needs to provide for 'class_names', 'feature_names' and 'categorical_names' in cases when the dataset is already one-hot encoded?

Thank you!

Best regards,
Kiril

**Comment by kirilgeorgiev82** [comment]
Got it. Don't bother to answer. I reverse-engineered based on the example. Cheers

**Comment by marcotcr** [comment]
Ugh, sorry I'm so slow in responding. I'm glad you figured it out : )
