### ISSUE TITLE
Anchor for Text NB data location?

### ISSUE THREAD

**Issue by samhavens** [marcotcr/anchor#25]
I love the paper and am excited to try out the code.

When running the Anchor for Text notebook, I ran into an issue with data. You define:

```python
def load_polarity(path='/home/marcotcr/phd/datasets/sentiment-sentences'):
```

and it's clear that the user has to change the path to the correct one on the machine the notebook is running... however, I looked at the site where the data is from, `# dataset from http://www.cs.cornell.edu/people/pabo/movie-review-data/`,  and it was hard to find the data you were using.

Once I figured it out, I updated the notebook a little to pull the data and extract it, so the notebook is more self-contained. Currently it is [on Google Colab](https://colab.research.google.com/drive/1QuWpE86ghWpDMdTtlk7sFmJZNY9NGz0S) but I am happy to open a PR with the changed notebook. Or just a change in the Readme to add a link to this Colab notebook.

**Comment by marcotcr** [comment]
Thanks! I think I will just link to your colab notebook in the readme, it's nice that the visualization at the end displays.
