### ISSUE TITLE
Can you make this available for conda install?

### ISSUE THREAD

**Issue by julianhatwell** [marcotcr/anchor#29]

**Comment by marcotcr** [comment]
I don't know what I would have to do, but [you can install pip packages inside conda](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages)

**Comment by julianhatwell** [comment]
OK. It's just that lime is available via conda-forge so I wonder why anchors couldn't be also. The reason I ask is that I have installed them on several machines and it is more convenient and reliable if everything can be done through conda environments. Thank you anyway. Great work.
