### ISSUE TITLE
submodular pick for anchor

### ISSUE THREAD

**Issue by Wwwwei** [marcotcr/anchor#34]
Hi, @marcotcr 
I am very interested in the submodular pick for anchor, but I find very little in the paper and code.
Where can I find more about it ?

**Comment by marcotcr** [comment]
Hey there. Since the coverage in anchor is very well defined, the submodular pick is super simple, it's just a basic set cover. You can see an example implementation [here](https://github.com/marcotcr/anchor-experiments/blob/master/utils.py#L335)
