### ISSUE TITLE
In Anchor, what is the number of instances in the neighbourhood when calculating coverage of the rule?

### ISSUE THREAD

**Issue by DiliSR** [marcotcr/anchor#35]
In Anchor, do the number of instances in the neighborhood is equal to the number of instances in the dataset which contains the global model predictions as same as the decision of the instance to be explained?

Thanks,

**Comment by marcotcr** [comment]
I'm not sure I quite grasp your question, so please reopen if my answer doesn't make sense.
We have [a hack](https://github.com/marcotcr/anchor/blob/master/anchor/anchor_base.py#L253) where we make sure to sample 10,000 instances to compute coverage on. We don't get predictions on these
