### ISSUE TITLE
'numpy.ndarray' object has no attribute 'feature_names'

### ISSUE THREAD

**Issue by alexlaurence** [marcotcr/anchor#37]
I get this error

`'numpy.ndarray' object has no attribute 'feature_names'`

When trying to execute

`explainer = AnchorTabular(model.predict, feature_names=X_test.columns.values.tolist())`

I tried to convert to numpy array, but that did not work. Should I convert to xgb.Dmatrix(...) ?

**Comment by marcotcr** [comment]
Take a look at what the arguments for the explainer should be [here](https://github.com/marcotcr/anchor/blob/master/anchor/anchor_tabular.py#L24)
