### ISSUE TITLE
Anchor explanation with regression

### ISSUE THREAD

**Issue by navdeep-G** [marcotcr/anchor#4]
* Have you looked into ways to explain regression models using Anchors? Would binning help in this case?

**Comment by marcotcr** [comment]
Yes, and yes. I've used anchor to explain functions on the output of regression models, such as:
1. If X and Y, Output > 100
2. If Z , 100 < Output < 120

I think using one sided binning functions (like 1 above) is more interpretable than two sided ones (like 2 above). In example 2 above, Z must be a very specific condition, as it can't lead to outputs smaller than 100 OR larger than 120. This makes for anchors that are too specific.

**Comment by navdeep-G** [comment]
Thanks @marcotcr! Will look at this further.

**Comment by manujosephv** [comment]
@marcotcr @navdeep-G  Although I understand how binning would help with this, I am not entirely clear on how to implement it in Anchor.

Is there any example or a notebook which handles Regression?
