### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by LHuysmans** [marcotcr/anchor#40]
I'm trying to use anchor on my dataset, but I run into dependencies issues. My environment currently uses sklearn 0.22, but when looking into the anchor code I see that an older version of SKlearn is used. 
The setup.py file shows that the packet has dependencies on numpy, scipy, spacy and scikit learn but does not specify the version. Could you give the versions of the packets that you used?

**Comment by arrayslayer** [comment]
Same issue. Please specify versions of dependencies.

**Comment by marcotcr** [comment]
Should be fixed by d86d99def867a3321bbe7789cf5f8955397c976a
