### ISSUE TITLE
Unexpected keyword argument 'categorical_features' in 'Anchor on tabular data.ipynb' 

### ISSUE THREAD

**Issue by rezacsedu** [marcotcr/anchor#42]
I'm experiencing "TypeError: __init__() got an unexpected keyword argument 'categorical_features'". Can you please suggest on how to fix it? 

![image](https://user-images.githubusercontent.com/14220009/75112664-1e0ba300-5646-11ea-8e5b-7aee66f4bf66.png)

**Comment by rezacsedu** [comment]
Previously, I was trying with Python3, but switching to Python 2 solved the issue. Hence, closing. 

Any plan to make things Python3 compatible? 

Thanks.

**Comment by marcotcr** [comment]
Just dropped python2 support, should work on python3 now.
