### ISSUE TITLE
AnchorTabularExplainer explain_instance

### ISSUE THREAD

**Issue by ri3017** [marcotcr/anchor#43]
Hi!
I am trying to use AnchorTabularExplainer to explain the predictions of a random forest classifier, but when calling explain_instance function I get this error: "ValueError: X has different shape than during fitting. Expected 4, got 11." I have checked that the train dataset and test dataset have the same shape.

Any suggestions of what can I do?

**Comment by marcotcr** [comment]
are you using an encoder? Can you paste some code snippets?

**Comment by ri3017** [comment]
Yes, I have used le = LabelEncoder() on the dataset before fitting the explainer and the classifier with the training/validation dataset to encode my categorical features.

**Comment by marcotcr** [comment]
Try the new version (since d86d99def867a3321bbe7789cf5f8955397c976a), in particular take a look at the tabular jupyter notebook  for how to use encoders.
