### ISSUE TITLE
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### ISSUE THREAD

**Issue by yosepppph** [marcotcr/anchor#44]
Hey, I'm working on a breast cancer dataset. When I call the explain_instace function, I get the above error message.

This is what the code looks like:
from anchor import anchor_tabular
explainer = anchor_tabular.AnchorTabularExplainer(np.asarray(["0","1"]),list(data.drop(columns=['id','diagnosis']).columns),x)
exp = explainer.explain_instance(X_test[0:1], classifier.predict, threshold=0.95)

I saw the same issue on Shap GitHub, and advice to use NumPy slices but still, that didn't work.

![Screen Shot 2020-04-29 at 5 06 55 PM](https://user-images.githubusercontent.com/17016910/80647158-07b20700-8a3c-11ea-91d6-291ae9195c56.png)

This is what the error log looks like

**Comment by marcotcr** [comment]
The first parameter should be a 1d numpy array, you are giving it a 2d numpy array of dimension (1, d).
Reopen if this doesn't fix it : )

**Comment by NoamKaufmanLin** [comment]
Hey, have the same issue while passing 1d array in the format of dataframe_row.values
