### ISSUE TITLE
Cannot install anchor on VS Code

### ISSUE THREAD

**Issue by kaixiyang** [marcotcr/anchor#46]
Hi there,
Is anchor suitable for VS Code? I tried to install / clone anchor / anchor_exp on VS Code but it kept showing error:
An error occurred while installing & ERROR: ERROR: Package installation failed...

I am wondering if I can only install anchor on Jupyter Notebook?

**Comment by marcotcr** [comment]
Sorry, I don't use VS Code at all so I don't know how handling packages on it work.
You can definitely install anchor without Jupyter Notebook (e.g. through `pip` in some unix-like environment or even on windows), but I don't know about VS.
