### ISSUE TITLE
anchor versioning

### ISSUE THREAD

**Issue by gautamsingaraju** [marcotcr/anchor#47]
The lastest package seems to be using Bert to perform text perturbation. The previous versions did not use transformers to perturb the utterances. However, when installing anchor from https://pypi.org/project/anchor-exp/, now requires installation of transformers. Could you please advice how versioning works for anchor? It would be ideal to get back to use the previous version if possible. Thank you.

**Comment by gautamsingaraju** [comment]
Wanted to report as well that I am getting the following error with latest pip installation, OSError: Model name `distilbert-base-cased' was not found in tokenizers model name list. tokenizer version installed in 2.9.1

**Comment by marcotcr** [comment]
It seems like you figured it out. I bumped the version from `0.0.0.6` to `0.0.1.0`
