### ISSUE TITLE
Number of samples in small datasets

### ISSUE THREAD

**Issue by mike1130694** [marcotcr/anchor#49]
I was analyzing the library and discovered that the parameter "num_samples" for anchor_tabular seems to be specified from the parameter coverage_samples in file anchor_base. The value is given to a default of 10,000 samples.
Do you see any problem on using such a large number of samples on relative small datasets? I am working with a dataset that has 1,000 instances. I will try to experiment with different values but would appreciate your input on this.

**Comment by marcotcr** [comment]
`coverage_samples` is only used to compute coverage, we don't actually get predictions on it. We're just bootstrapping from the original dataset to estimate the coverage of different features (if it's tabular) or understanding the perturbation function (if it's text or images).
The actual number of samples is not an input to the explainer - this is an adaptive algorithm, it will use as many samples as needed until it has an anchor with high probability.
