### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by Aphaniteja** [marcotcr/anchor#5]
Where can I download the datasets used in the notebooks

**Comment by marcotcr** [comment]
The text notebook had [this link](http://www.cs.cornell.edu/people/pabo/movie-review-data/) on it.
The tabular notebook uses the traditional adult dataset. You can download it from [here](https://github.com/marcotcr/anchor-experiments/blob/master/datasets/adult/adult.data).

**Comment by alfonsomhc** [comment]
I had the same problem. I would suggest to add this information in the tabular notebook :)
