### ISSUE TITLE
Sp anchor 

### ISSUE THREAD

**Issue by adityakumar04** [marcotcr/anchor#52]
Hello Marco,

Could you provide more details on how to use the SP anchor. Also how will the precision and coverage be defined in case of SP -anchor ?

**Comment by marcotcr** [comment]
It only really makes sense for tabular data, where you can compute coverage / precision on held out data.
Take a look at [this](https://github.com/marcotcr/anchor-experiments/blob/master/utils.py#L335). It's very simple: given a list of anchors, see where they apply, and greedily pick the anchor that increases total coverage the most.

**Comment by adityakumar04** [comment]
Thanks for the answer Marco, However what should be the list of anchors ?. Do we compute list of anchors separately and then pass them as a list or is there a function to automatically pick the best list of anchors ?

**Comment by adityakumar04** [comment]
Hello Marco, Any help on the above issue will be greatly appreciated.

**Comment by marcotcr** [comment]
If you have a validation dataset (`data`), just compute anchors for each element and put them in a separate list `explanations`. The submodular procedure will take this list and pick the best `k` (default 5), where 'best' is defined as 'maximum coverage'.
