### ISSUE TITLE
Example only shows first few words of given text

### ISSUE THREAD

**Issue by saranoor** [marcotcr/anchor#56]
I am following the example for ‘Anchor for text’. The only difference is I am using my own dataset. My data is labelled as ‘depressed’ and ‘not depressed’. One thing I don’t understand is when I print the examples it includes the first few words from the entire text given to anchor explainer. For eg : following is the text I am giving to anchor

![image](https://user-images.githubusercontent.com/44978518/89938657-cd343a80-dbe4-11ea-9e5e-0b3b037360ca.png)

When I print the examples where anchor apply, and model predicts ‘depressed’ or ‘not depressed’. It only prints the first few words from the whole text. 

![image](https://user-images.githubusercontent.com/44978518/89938773-fa80e880-dbe4-11ea-8c95-fa3cf6971769.png)

Can you please explain why it is not taking into account entire given text?

**Comment by marcotcr** [comment]
sorry for the delay in responding. We were truncating strings at 80, and I guess I never noticed because I didn't try longer strings. Fixed in 00a3ee1c26f91ce1e4433a21aa628e766eb709c6
