### ISSUE TITLE
About the 'lending club' dataset

### ISSUE THREAD

**Issue by der1997** [marcotcr/anchor#60]
Hello，
I want to use the 'lending club' dataset in my paper to do experiment. While the website has the terms of use. I can't confirm if I can use it for free. And when I try to use the 'anchor' I notice that you used it . So I wonder if you paid for the usage or just used it for free? Hope you could answer my question. Thank you so much.
Shucen Ma

**Comment by marcotcr** [comment]
It wasn't paid when I used it. There seem to be versions available for free, e.g [here](https://www.kaggle.com/wordsforthewise/lending-club)

**Comment by der1997** [comment]
Thank you for your replying!
Best wishes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "marcotcr/anchor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月19日(星期六) 凌晨1:57
收件人:&nbsp;"marcotcr/anchor"<anchor@noreply.github.com&gt;;
抄送:&nbsp;"1053911540"<1053911540@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [marcotcr/anchor] About the 'lending club' dataset (#60)





 
It wasn't paid when I used it. There seem to be versions available for free, e.g here
