### ISSUE TITLE
use_bert unknown parameter

### ISSUE THREAD

**Issue by tomasMizera** [marcotcr/anchor#61]
Hi @marcotcr, thanks for your work!

I am trying to use Anchors in my thesis but I do not quite understand current Anchors version on pip. I am using `AnchorText` class and wanted to experiment with BERT. However, current version ([0.0.2.0](https://pypi.org/project/anchor-exp/0.0.2.0/)) seems not to have parameter `use_bert` as it was with previous version [0.0.1.2](https://pypi.org/project/anchor-exp/0.0.1.2/). After looking at code and some issues (mainly #57) my guess is that now when `use_unk_distribution` is set to False, BERT is used automatically? 

What is misleading is that I can still see `use_bert` in codebase [here on GitHub](https://github.com/marcotcr/anchor/blob/master/anchor/anchor_text.py#L103), however it is not a case for pip version.

![image](https://user-images.githubusercontent.com/22449698/102834721-24e57c80-43f5-11eb-9e61-49fae650af3f.png)

**Comment by EmanueleLM** [comment]
I think they use bert now as default. Just remove it.
Without bert, there were compatibilty issues with the latest version of Spacy and the en_core_web_lg.
Check this out: https://github.com/marcotcr/anchor/issues/57

Emanuele
